### ISSUE TITLE
Reconstructed point clouds cannot be displayed when the IMU_RGBD mode is used

### ISSUE THREAD

**Issue by zhangzscn** [luigifreda/plvs#10]
I am testing the PLVS algorithm using kinectDK, using the same configuration file in both IMU_RGBD and RGBD modes. In RGBD mode, point clouds can be displayed normally, but in IMU_RGBD mode, point clouds cannot be displayed. Why is that?
[kinectDK.txt](https://github.com/luigifreda/plvs/files/13374346/kinectDK.txt)

**Comment by luigifreda** [comment]
Thank you for the feedback. Fixed with with new commit.
