### ISSUE TITLE
Ask about progress and ask for help.

### ISSUE THREAD

**Issue by kkmd66** [luigifreda/plvs#11]
May I ask, is the effect in the paper now reproducible through existing code? I tried to reproduce it, but algorithms like EDLine don't seem to have seen it yet. If it's my problem, can you tell me the code command? Thank you.

**Comment by luigifreda** [comment]
Hi,
Could you please share what is your YAML settings file and your launch script/command? 
Which is your target dataset? 
Which sensor are you using? Mono, stereo, RGBD?

Did you read the README.md? Did you read the [new features file](https://github.com/luigifreda/plvs/blob/master/new_features.md)?
Did you set  `Line.on: 1`?

**Comment by kkmd66** [comment]
I tried running PLVSII again, and the RGBD camera running effect under the TUM data set was amazing. I admire it very much.

But below I encountered a new problem, I hope you can help.

1. I found that in Stereo mode or Stereo-Inertial mode, only line features can be added (other new feature parameters are set to 0). When I add new feature parameters such as PointCloudMapping.on: 1, the system will crash with a segmentation fault. Is this caused by my problem?

Some detailed documents below.
Run command: ./run_tum_vi_stereo.sh or ./run_tum_vi_stereo_inertial.sh
Terminal output: terminal_output_run_tum_vi_stereo.txt or terminal_output_run_tum_vi_stereo_inertial.txt
YAML file: TUM-VI_rectified_stereo.yaml or TUM-VI_rectified_stereo_inertial.yaml

2. I found that when the stereo mode of PLVSII only turns on the point and line features, in the dataset-outdoors8_512_16 sequence of the TUM-VI dataset, after leaving the building, the trajectory will drift circularly at a constant speed (as shown in the figure stereo_TUM -VI-dataset-outdoors8_512_16_point_line_1.png, stereo_TUM-VI-dataset-outdoors8_512_16_point_line_2.png). It seems to be caused by fisheye camera distortion.

3. Similar to the second doubt, I found that the stereo-inertial of PLVSII, when only the point and line features are turned on, in the dataset-outdoors8_512_16 sequence of the TUM-VI dataset, is in a specific place (as shown in the figure stereo-inertial_TUM -VI-dataset-outdoors8_512_16_point_line_1.png, stereo-inertial_TUM-VI-dataset-outdoors8_512_16_point_line_2.png) will cause the IMU to run away.
