### ISSUE TITLE
Is catkin-tools needed? - Fix install_dependencies.sh for fresh ubuntu 20.04 installation

### ISSUE THREAD

**Issue by LukasPoque** [luigifreda/plvs#12]
I tried to run the `install_dependencies.sh` on a completely new Ubuntu 20.04 system. In the end, there was an error message indicating catkin-tools are missing `E: Unable to locate package python3-catkin-tools`

Looking at docs of it (https://catkin-tools.readthedocs.io/en/latest/installing.html) it states that Ubuntu needs additional configuration. After executing the four commands, catkin tools are successfully installed.

Can someone reproduce the error? And if catkin-tools are needed for the project, should I create a PR with the changed  `install_dependencies.sh`?

**Comment by luigifreda** [comment]
Hi,
thank you for the feedback. That issue is now fixed. 
Catkin tools are used for building ROS stuff.
