### ISSUE TITLE
 The RGBD camera running effect under the TUM data set was amazing.But below I encountered a new problem, I hope you can help.

### ISSUE THREAD

**Issue by dansonZhang** [luigifreda/plvs#13]
I tried running PLVSII again, and the RGBD camera running effect under the TUM data set was amazing. I admire it very much.

But below I encountered a new problem, I hope you can help.

I found that in Stereo mode or Stereo-Inertial mode, only line features can be added (other new feature parameters are set to 0). When I add new feature parameters such as PointCloudMapping.on: 1, the system will crash with a segmentation fault. Is this caused by my problem?
Some detailed documents below.
Run command: ./run_tum_vi_stereo.sh or ./run_tum_vi_stereo_inertial.sh
Terminal output: terminal_output_run_tum_vi_stereo.txt or terminal_output_run_tum_vi_stereo_inertial.txt
YAML file: TUM-VI_rectified.yaml(only modified PointCloudMapping.on: 1)

I found that when the stereo mode of PLVSII only turns on the point and line features, in the dataset-outdoors8_512_16 sequence of the TUM-VI dataset, after leaving the building, the trajectory will drift circularly at a constant speed (as shown in the figure stereo_TUM -VI-dataset-outdoors8_512_16_point_line_1.png, stereo_TUM-VI-dataset-outdoors8_512_16_point_line_2.png). It seems to be caused by fisheye camera distortion.

Similar to the second doubt, I found that the stereo-inertial of PLVSII, when only the point and line features are turned on, in the dataset-outdoors8_512_16 sequence of the TUM-VI dataset, is in a specific place (as shown in the figure stereo-inertial_TUM -VI-dataset-outdoors8_512_16_point_line_1.png, stereo-inertial_TUM-VI-dataset-outdoors8_512_16_point_line_2.png) will cause the IMU to run away.

**Comment by kkmd66** [comment]
![stereo_TUM-VI-dataset-outdoors8_512_16_point_line_2](https://github.com/luigifreda/plvs/assets/57592105/652e31d6-79ca-4928-94e1-a0afc93e3698)
![stereo_TUM-VI-dataset-outdoors8_512_16_point_line_1](https://github.com/luigifreda/plvs/assets/57592105/1daff19b-6e05-4404-9ade-dafd14d600f7)
![stereo-inertial_TUM-VI-dataset-outdoors8_512_16_point_line_2](https://github.com/luigifreda/plvs/assets/57592105/3c4a075a-f531-4834-aa4b-d3614426ad7d)
![stereo-inertial_TUM-VI-dataset-outdoors8_512_16_point_line_1](https://github.com/luigifreda/plvs/assets/57592105/69da279a-c86d-47f9-ab0c-f6eed745e14a)
[terminal_output_run_tum_vi_stereo.txt](https://github.com/luigifreda/plvs/files/13466568/terminal_output_run_tum_vi_stereo.txt)
[terminal_output_run_tum_vi_stereo_inertial.txt](https://github.com/luigifreda/plvs/files/13466569/terminal_output_run_tum_vi_stereo_inertial.txt)

**Comment by kkmd66** [comment]
[terminal_output_run_tum_vi_stereo.txt](https://github.com/luigifreda/plvs/files/13466574/terminal_output_run_tum_vi_stereo.txt)
[terminal_output_run_tum_vi_stereo_inertial.txt](https://github.com/luigifreda/plvs/files/13466575/terminal_output_run_tum_vi_stereo_inertial.txt)

**Comment by kkmd66** [comment]
![stereo_TUM-VI-dataset-outdoors8_512_16_point_line_2](https://github.com/luigifreda/plvs/assets/57592105/0a177713-d02a-4181-a49e-8073abcdc153)
![stereo_TUM-VI-dataset-outdoors8_512_16_point_line_1](https://github.com/luigifreda/plvs/assets/57592105/3b550947-567a-4f2b-848a-6e4fa124ae50)
![stereo-inertial_TUM-VI-dataset-outdoors8_512_16_point_line_2](https://github.com/luigifreda/plvs/assets/57592105/41dd1071-091c-4041-b653-ffe67cb469a5)
![stereo-inertial_TUM-VI-dataset-outdoors8_512_16_point_line_1](https://github.com/luigifreda/plvs/assets/57592105/6a862eeb-4b3e-4ec1-84dd-d112bfd50deb)

**Comment by luigifreda** [comment]
Hi, 
thanks for the post.

Some preliminary questions:
- Can you please share how you installed PLVS? Did you use a local install of opencv as suggested?  
- Does your computer have a GPU? 
- Can you share the log you obtain by running `git diff >& /tmp/log.txt`? 

# 1
> I found that in Stereo mode or Stereo-Inertial mode, only line features can be added (other new feature parameters are set to 0). When I add new feature parameters such as PointCloudMapping.on: 1, the system will crash with a segmentation fault.

I don't see this problem both on Euroc and TUM-VI. I can enable ` PointCloudMapping.on: 1` without problems. 
Can you test on Euroc if you have the same problem? If yes, can you enter in `Thirdparty/libelas-gpu/build` and run `./test_gpu` and copy-paste here what you get as stdout?  

I see you are getting that problem on the *TUM-VI slide3* dataset. 
- Can I ask why you selected that specific dataset to test point cloud mapping that is based on stereo depth estimation? 
- Do you think static stereo matching can get a reasonable depth estimation from a stereo pair like this?
![Screenshot from 2023-11-26 22-05-51](https://github.com/luigifreda/plvs/assets/10080262/d3a4e4af-2413-44ee-8b41-3bc33dd87acd)
  
I am now checking the dataset... 

# 2 

> I found that when the stereo mode of PLVSII only turns on the point and line features, in the dataset-outdoors8_512_16 sequence of the TUM-VI dataset, after leaving the building, the trajectory will drift circularly at a constant speed (as shown in the figure stereo_TUM -VI-dataset-outdoors8_512_16_point_line_1.png, stereo_TUM-VI-dataset-outdoors8_512_16_point_line_2.png). It seems to be caused by fisheye camera distortion.

I can reproduce this problem. I solved it by using the "far" configuration (`TUM-VI_far.yaml`) that ignore points that are too far away.  I am pushing some small changes that allow to correctly load the "far" configuration.

In TUM-VI, using a rectified stereo pair allows to use the lines and volumetric mapping. However, it requires a pre-processing (that acts as a pre-filter on the images) and reduces the FOV of the camera. In general, this affects both SLAM robustness and accuracy.
