### ISSUE TITLE
Point-Line mode using fisheye camera

### ISSUE THREAD

**Issue by HJMGARMIN** [luigifreda/plvs#14]
Hello, I found that when using fisheye cameras(like TUM-VI dataset), the line features only works by setting "Camera.needRectification: 1  # only with KannalaBrandt8
Camera.fovScale: 0.65         # only with KannalaBrandt8".
I want to know if I can use line features directly in fisheye camera like below figure:
![image](https://github.com/luigifreda/plvs/assets/52454672/9280a1f2-eef4-442f-9ce2-7c7392e8fffa)

**Comment by luigifreda** [comment]
Hi, 
thanks for your feedback. Yes, that's correct. 
When using fisheye cameras (for instance, TUM-VI dataset), the line features are only supported by setting 
```
"Camera.needRectification: 1 # only with KannalaBrandt8
Camera.fovScale: 0.5 # only with KannalaBrandt8"
```

At present, the extraction of line features directly on fisheye cameras is NOT supported. This is on the TODO list. 
Thanks for sharing the paper.

**Comment by luigifreda** [comment]
Hi, 
I just pushed a first version of line detection, tracking, and visualization (AR by using a shader) for fisheye cameras: Now, you are not compelled anymore to force stereo rectification.

**Comment by HJMGARMIN** [comment]
Thanks for your great work! However, when I try the fisheye version on TUM-VI dataset, I met the following problems. Can you help me?
![image](https://github.com/luigifreda/plvs/assets/52454672/39078209-e454-4518-8119-7bb614cddba6)

**Comment by luigifreda** [comment]
Thanks! It should be fixed now.
