### ISSUE TITLE
 Is the process of using mono lens the same as orb_slam2?

### ISSUE THREAD

**Issue by BlueMoonChan** [luigifreda/plvs#15]
I have built ros_ws, do I need to create a build file like orb slam2 and then run "cmake ... " and "make"?
My past experience with orb slam2 has been to use "rosrun ORB_SLAM2 Mono /home/b104/ catkin_ws/src/ORB_SLAM2/Vocabulary/ORBvoc.txt /home/b104/ catkin_ws/src/ORB_SLAM2/ Examples/ROS/ORB_SLAM2/Asus.yaml " Turn on the camera and do slam, is it the same in PLVS?

P.S:I'm not a native English speaker and I only use orb_slam2 twice, so apologies if this is unclear.

**Comment by luigifreda** [comment]
Hi, 
Once you have built `ros_ws`, you can enter in that folder and `source devel/setup.bash` and  run`rosrun plvs Mono ...` or `rosrun plvs RGBD ...`  etc
