### ISSUE TITLE
TimeUtils

### ISSUE THREAD

**Issue by enginksz** [luigifreda/plvs#2]
Hello,

Thank you for your great work.

The ./build.sh is giving an error because it can't find the TimeUtils.h file.

In /home/eng/plvs/src/PointCloudMapping.cc at line 46 and /home/eng/plvs/src/PointCloudKeyFrame.cc at line 26, it's showing a fatal error due to the absence of TimeUtils.h.

Also, the file is not present in the src directory.

Can you assist with this matter?

**Comment by enginksz** [comment]
Thanks for adding.

Random.h, Random.cpp, Timestamp.pp and Timestamp.h files should be included in the DUtils folder. (can be withdrawn from the specified repo: https://github.com/dorian3d/DLib)

(I did not get any errors in the other steps, additionally I downloaded the g20_new / 20230223_git version.)

When I run the command : eng@eng:~/plvs$ ./build_plvs.sh I get the following error:
....
....
....
--CUDA_NVCC_FLAGS:
-- Configuring done (0.2s)
-- Generating done (0.6s)
-- Build files have been written to: /home/eng/plvs/build
[ 1%] Building CXX object CMakeFiles/plvs.dir/src/System.cc.o
[ 1%] Building CXX object CMakeFiles/plvs.dir/src/Tracking.cc.o
[ 2%] Building CXX object CMakeFiles/plvs.dir/src/LocalMapping.cc.o
[ 3%] Building CXX object CMakeFiles/plvs.dir/src/LoopClosing.cc.o
....
....
....
make[2]: *** [CMakeFiles/plvs.dir/build.make:90: CMakeFiles/plvs.dir/src/Tracking.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:181: CMakeFiles/plvs.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by luigifreda** [comment]
Hi, 
thanks for your feedback. Now, everything should be fixed.
If you want to install and use a new g2o version (tested), use `install_local_g2o_new.sh` and set the option `WITH_G2O_NEW` to `ON` in the main CMakeList.txt of PLVS.
