### ISSUE TITLE
ROS Error

### ISSUE THREAD

**Issue by HJMGARMIN** [luigifreda/plvs#21]
Hello, when I deploy ROS melodic, I met problems as follows:
![image](https://github.com/luigifreda/plvs/assets/52454672/88e3369a-680d-4992-9985-270a0a37b36d)

**Comment by luigifreda** [comment]
Hi,
I am not sure how to help (the error is not reported in English). In any case, PLVS is now supported under noetic. You can use [rosdocker](https://github.com/luigifreda/rosdocker).
