### ISSUE TITLE
The same 3D line is back-projected into different lines

### ISSUE THREAD

**Issue by HJMGARMIN** [luigifreda/plvs#22]
Regarding this part of the description, does it mean that for a 3D line in the same space, its endpoints may not be exactly the same when the corresponding line segments in different observation frames are back-projected into the 3D space?Then, this article also mentions P and Q when representing 3D lines. Is there a specific code description for PQ in this picture?
![image](https://github.com/luigifreda/plvs/assets/52454672/396fda21-78e6-4bc0-85e0-f7bd8e53ac87)

**Comment by luigifreda** [comment]
Hi,

> Regarding this part of the description, does it mean that for a 3D line in the same space, its endpoints may not be exactly the same when the corresponding line segments in different observation frames are back-projected into the 3D space?

Yes. In the paper (Sect. III.C), there are a couple of sentences that motivate this point:
_Due to noise, possible occlusions, and other factors, the 3D line segment l may not be fully observed by the camera and endpoints are often inconsistent across images [8]. Furthermore, a 3D line segment can be fragmented into multiple line segments (belonging to the same line in 3D)._

> Then, this article also mentions P and Q when representing 3D lines. Is there a specific code description for PQ in this picture?

Yes. The `MapLine` class hosts a representation of the two 3D points `P` (start) and `Q` (end) of the 3D line segment (in world coordinates):
```
    Eigen::Vector3f mWorldPosStart; 
    Eigen::Vector3f mWorldPosEnd;   
```
The 2D image observations of the `MapLine` are the 2D keylines `cv::line_descriptor_c::KeyLine`, each one hosting the image coordinates of the start and end points (pixel coordinates).

Hope this helps.

**Comment by HJMGARMIN** [comment]
For 2D lines matched in two frames, they are back-projected to the same line segment in three-dimensional space. If their back-projected space endpoints do not coincide, will P and Q make the two back-projected line segments coincide?
