### ISSUE TITLE
Can't compile without CUDA

### ISSUE THREAD

**Issue by D1st3f** [luigifreda/plvs#25]
When building I get error, so my example files don't create. 

Specify Cuda Toolkit Root Dir even in noetic without cuda

**Comment by luigifreda** [comment]
I am testing with [rosdocker](https://github.com/luigifreda/rosdocker) by using the simple `noetic` image available therein.
This is what I get when CUDA is not found. 

![Screenshot from 2024-03-18 23-48-51](https://github.com/luigifreda/plvs/assets/10080262/6c231910-ccf2-4020-90ee-2da8b7788809)

**Comment by luigifreda** [comment]
Pushed a fix. Now, you should be able to build the code.
