### ISSUE TITLE
Segmentation error

### ISSUE THREAD

**Issue by D1st3f** [luigifreda/plvs#27]
I have bad result form segmentation:
![314063680-37d1877b-75e9-4143-bc42-f289d0654a2d](https://github.com/luigifreda/plvs/assets/76536480/e59adeb2-57c9-4728-80e1-4e92994a1f36)

And when segmentation off:
![314063629-c7a10e8b-6835-4a8a-a6df-820c5fcbeaa2](https://github.com/luigifreda/plvs/assets/76536480/df00cfb6-b84b-4a7b-bd33-b939bb71f32d)

Also:
PointCloudMapping.type: "octree_point"
Segmentation.on: 1

Another GUI screenshots:
![314064709-d6f5657c-f09a-4540-acbd-3b7ffe4d0c94](https://github.com/luigifreda/plvs/assets/76536480/f3f24612-8efb-424c-b616-2b12f1c8a4cb)

Look's like something broken i normals.

P.S. Tried without touching sliders in GUI, same result.

**Comment by luigifreda** [comment]
Is this thread related to your issue? 
https://github.com/luigifreda/plvs/issues/5

Can you share more about your OS ans HW configurations?

**Comment by D1st3f** [comment]
Yup, ubuntu 23 + rosfocker on Google cloud platform, 8 cores cpu atd nvidia T4.

#5 Issue similar, but he have a segmentation.

**Comment by luigifreda** [comment]
Thanks for your feedback. Could you share the exact install procedure you followed? 

At the moment, there is no full support for Ubuntu 23. That's a WIP. I have to investigate. It may also be a visualization problem. 

In the meantime, you can use [rosdocker](https://github.com/luigifreda/rosdocker) with noetic or noetic_cuda images (see the instructions in the repo).

**Comment by D1st3f** [comment]
I used rosdocker noetic but on cloud machine with Ubuntu 23.

**Comment by luigifreda** [comment]
Could you please share the exact install procedure you followed?

**Comment by D1st3f** [comment]
Clean Ubuntu 23, downloaded ros-docker, build ros-docker noetic, runed ros-docker noetic. To shared folder git cloned plsv and downloaded dataset. Instaled dependecies + local opevcv + builded plsv. Fixed path to dataset + changed yaml file to get segmentantions.

**Comment by luigifreda** [comment]
I believe you are getting a visualization problem. I am not sure how to reproduce it. I don't have a google cloud machine.

**Comment by D1st3f** [comment]
I will try on my own pc and give you feedback

**Comment by FishofJLlake** [comment]
I reproduced this issue in the WSL2 environment on Windows. What could be the problem?

**Comment by luigifreda** [comment]
It seems using opengl shaders under wsl is not super trivial
https://stackoverflow.com/questions/74834823/access-geometry-shaders-on-wsl2-ubuntu-22-04-lts
