### ISSUE TITLE
./install_local_opencv.sh

### ISSUE THREAD

**Issue by CoderDoubleTen** [luigifreda/plvs#31]
CMakeFiles/opencv_highgui.dir/src/window.cpp.o：在函数‘cv::setOpenGlDrawCallback(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void (*)(void*), void*)’中：
window.cpp:(.text._ZN2cv21setOpenGlDrawCallbackERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPFvPvES8_+0x3f)：对‘cvSetOpenGlDrawCallback’未定义的引用
CMakeFiles/opencv_highgui.dir/src/window.cpp.o：在函数‘cv::setOpenGlContext(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：
window.cpp:(.text._ZN2cv16setOpenGlContextERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x31)：对‘cvSetOpenGlContext’未定义的引用
CMakeFiles/opencv_highgui.dir/src/window.cpp.o：在函数‘cv::updateWindow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：
window.cpp:(.text._ZN2cv12updateWindowERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x31)：对‘cvUpdateWindow’未定义的引用
collect2: error: ld returned 1 exit status
modules/highgui/CMakeFiles/opencv_highgui.dir/build.make:262: recipe for target 'lib/libopencv_highgui.so.4.8.0' failed
make[2]: *** [lib/libopencv_highgui.so.4.8.0] Error 1
CMakeFiles/Makefile2:4345: recipe for target 'modules/highgui/CMakeFiles/opencv_highgui.dir/all' failed
make[1]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/all] Error 2
make[1]: *** 正在等待未完成的任务...

**Comment by luigifreda** [comment]
Hi,
Could you share your OS and system configuration?
