### ISSUE TITLE
How to save the segmented point cloud map

### ISSUE THREAD

**Issue by langlangqunawan** [luigifreda/plvs#34]
Your work is really amazing! I'd like to ask how to save the segmented point cloud map?

**Comment by luigifreda** [comment]
Hi, thanks for your feedback. 
You can press the "Save" button on the GUI. It will save both the sparse and dense maps. 
In particular, the method `PointCloudMapping::SaveMap()` will be called to save a ply in your working folder. 
The segmented point cloud is a custom one. Take a look here: 
https://github.com/luigifreda/plvs/blob/master/include/PointSurfelSegment.h
If you open it with [cloudcompare](https://www.danielgm.net/cc/) then it will find the custom label fields.
