### ISSUE TITLE
How to save KeyframeTrajectory.txt

### ISSUE THREAD

**Issue by qinkai0127** [luigifreda/plvs#35]
nice job~！But when i run the rgbd_tum, i don't find the ""KeyFrameTrajectiory.txt"and other information such like "median tracking time" can't show in the terminal

**Comment by luigifreda** [comment]
Hi, thanks for your feedback. 
The run scripts (including the script `Scripts/run_tum_rgbd.sh` you are using) call the script `Scripts/move_output_to_results.sh` that moves the output files (such as `KeyFrameTrajectiory.txt`) into `Scripts/Results` to keep the `Scripts` folder a bit clean. You can find everything therein.
