### ISSUE TITLE
./build_ros_catkin.sh

### ISSUE THREAD

**Issue by CQnancy** [luigifreda/plvs#36]
When I finish running ./build_ros_catkin.sh file, I cannot run ./ros_xterm_tum_rgbd.sh
rosrun PLVS 
octomap.launch            plvs.rviz                 rviz_plvs.launch
package.xml               r200_nodelet_rgbd.launch  xtion.launch
I don't have RGBD....

**Comment by CQnancy** [comment]
rosrun plvs RGBD ~/ros_was/src/plvs/Vocabulary/ORBvoc.txt ~/ros_ws/src/plvs/Examples_old/RGB-D/TUM1.yaml
[rosrun] Couldn't find executable named RGBD below ~/ros_ws/src/plvs/Examples_old/ROS/plvs
[rosrun] Found the following, but they're either not files,
[rosrun] or not executable:
[rosrun]  ~/ros_ws/src/plvs/Examples_old/ROS/plvs/build/devel/lib/plvs/RGBD

**Comment by CQnancy** [comment]
rosrun plvs RGBD ~/plvs/Vocabulary/ORBvoc.txt ~/plvs/Settings/ros/TUM1_ros.yaml /camera/rgb/image_raw:=/camera/rgb/image_color camera/depth_registered/image_raw:=/camera/depth/image 
Segmentation fault (core dumped)
I don't know how to solve it

**Comment by luigifreda** [comment]
Hi, 
I've tested it again (building from scratch) and it works. 
You first need to build with `./build_ros_catkin.sh` (if you already did it please clean with `rm -Rf ros`) and then you just need to launch `./ros_xterm_tum_rgbd.sh` (assuming you have properly set the dataset path therein) . Please, double-check you have install xterm with `sudo apt install -y xterm`). You don't need anything else. 

Side note that is contained in the run script 
```
# IMPORTANT: Refer to https://github.com/ros/ros_comm/issues/82
# Playing TUM rosbags at a normal rate is not possible since the clock publication is not reliable. 
# In order to solve the problem the bags must be decompressed with rosbag decompress! 
# A quick fix is to play the bags with half rate (it's very likely this gives time to the decoding process to finish its job on time so that clock data publication can be normally performed.
```
