### ISSUE TITLE
Weird behaviour with Stereo_Inertial

### ISSUE THREAD

**Issue by krzmancd** [luigifreda/plvs#38]
Greetings,

We have a Nerian Scarlet stereo camera, that we're trying to setup Stereo SLAM on.
The PLVS2 works great with just just stereo camera, without IMU, however, when using Stereo_Inertial, with IMU, the map keeps resetting, with the following warning:

The imu is being published with ~200Hz.

```bash
Tracking::UpdateFrameIMU() - update on map 0
Tracking::UpdateFrameIMU() - update on map 0
******************************
Optimizer::FullInertialBA() 
******************************
WARNING: NO INERTIAL LINK TO PREVIOUS FRAME - KF id: 0
Preparing keyframe, id = 0 (Bad: 0, LBA count: 8) (#queued: 10)
stereo processing (libelas)
Global Bundle Adjustment finished
Updating map ...
Map updated!
Fail to track local map!
Track lost for less than one second...
IMU is not or recently initialized. Resetting active map...
PointCloudMapping::Reset() - start 
Preparing keyframe, id = 1 (Bad: 0, LBA count: 8) (#queued: 9)
stereo processing (libelas)
Preparing keyframe, id = 2 (Bad: 0, LBA count: 8) (#queued: 8)
stereo processing (libelas)
Preparing keyframe, id = 3 (Bad: 0, LBA count: 7) (#queued: 7)
stereo processing (libelas)
Preparing keyframe, id = 4 (Bad: 0, LBA count: 6) (#queued: 6)
stereo processing (libelas)
Preparing keyframe, id = 5 (Bad: 0, LBA count: 5) (#queued: 5)
stereo processing (libelas)
Preparing keyframe, id = 6 (Bad: 0, LBA count: 4) (#queued: 4)
stereo processing (libelas)
Preparing keyframe, id = 7 (Bad: 0, LBA count: 3) (#queued: 3)
stereo processing (libelas)
Preparing keyframe, id = 8 (Bad: 0, LBA count: 2) (#queued: 2)
stereo processing (libelas)
[ INFO] [1732625110.029469331]: 26.0 fps
Preparing keyframe, id = 9 (Bad: 0, LBA count: 1) (#queued: 1)
stereo processing (libelas)
PointCloudMapping::Reset() - end
Active map Resetting
lastKeyframeIndex: 0
Resetting Local Mapper...
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Resetting current map in Local Mapping...
LM: End resetting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
done
Resetting Loop Closing...

```

Do you maybe know, what the problem could be? Is the IMU data bad? I did notice that the `linear_acceleration` values are very "discreet". As seen in the image:
![nerian_imu](https://github.com/user-attachments/assets/db51cf0d-ddbb-48fc-8425-25e8689bb223)

Angular velocity values are pretty good, however the linear acceleration values aren't, with multiple sequential readings reading the same values.

Update: I tried with another external IMU, and the result was the same.
What format must data in IMU be? m/s^2? g? Should gravity be included, or excluded?

Thanks for your help!

**Comment by Krzo99** [comment]
Hey,

We have calibrated the camera using Kalibr, however the values did not make sense.

After that, we have used the calibration, provided by the manufacturer.

We'll try calibrating again & provide a bag file as soon as possible.

Thanks!

**Comment by krzmancd** [comment]
Hey,

Finaly circling back on this issue!
We're providing the launch, config & bag files for you to test for yourself.
[data.tar.xz](https://guardiaris-my.sharepoint.com/:u:/p/ogrinj/EYq6S98lWutCrOOORdE4-98B9e7S9UjlWY4hGpotdadgmA?e=KtLH30)
Thanks for your help!

Have a nice day.

**Comment by luigifreda** [comment]
I am not able to access the dataset. I am requested to log in and cannot do it. 
Please share it in another way without any login request.

**Comment by krzmancd** [comment]
Opa, my bad.
The correct link is: https://guardiaris-my.sharepoint.com/:u:/p/ogrinj/EYq6S98lWutCrOOORdE4-98B43z7jYzQOoLFyWu3zLX3bQ?e=GJMniD

**Comment by luigifreda** [comment]
mmm... there is something weird in the file sizes
![Screenshot from 2025-01-09 20-09-30](https://github.com/user-attachments/assets/6bc74c5c-498b-4cb9-bade-c51f0e5c517e)

plus the video is completely static

**Comment by krzmancd** [comment]
This one should be OK now, sorry for the inconvenience:
[data](https://guardiaris-my.sharepoint.com/:u:/p/krzmancd/EUKtoHJJOvhOsDo2g4I1jDYBQLtYr0fFWD47g-JO8g89QA?e=vGW7ca)

The video is just static, yes. The robot is not moving, but even in these conditions, the slam with IMU fails.

**Comment by luigifreda** [comment]
Could you explain how a visual-inertial system can be correctly initialized with a static input sequence? 
Could you let me know if you studied the problem in detail?
Do you think the system is observable with a static input sequence?

**Comment by krzmancd** [comment]
It's not static. SLAM must work if the robot is standing still.
The .bag contains multiple images, from a robot that is standing still and imu data.
The images are different, they are not the same image. The robot is standing still.
I don't understand the question. Maybe I haven't studied the issue enough? Does the robot need to move at the start of SLAM init?
