### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by enginksz** [luigifreda/plvs#4]
Hello,

Attached is the result I got when I ran the gbd_dataset_freiburg2_pioneer_slam3 dataset as an example.

![rgbd_2_slam3](https://github.com/luigifreda/plvs/assets/38870269/69fc2f9c-3bf4-478a-b36d-49e150b56a8f)

I can't see the Point Cloud output. I deleted Pangolin and reinstalled it, but I couldn't figure out what the problem was.

**Comment by luigifreda** [comment]
Hi,
thanks for the feedback. You need to activate it. 
Go into 
https://github.com/luigifreda/plvs/blob/master/Examples_old/RGB-D/TUM2.yaml

Set `PointCloudMapping.on: 1` here 
https://github.com/luigifreda/plvs/blob/master/Examples_old/RGB-D/TUM2.yaml#L161

and play with the different methods by changing `PointCloudMapping.type` here
https://github.com/luigifreda/plvs/blob/master/Examples_old/RGB-D/TUM2.yaml#L165
