### ISSUE TITLE
some  errors about ./build_thirdparty.sh

### ISSUE THREAD

**Issue by coutrol** [luigifreda/plvs#40]
Hello, when I run ./build_thirdparty.sh, I encounter errors during the make process for chisel_server and voxblox_server. How can I resolve these errors? I look forward to your response.
![微信图片_20241129184601](https://github.com/user-attachments/assets/2e10b6c1-2006-4c74-83c1-71784da793f3)
![微信图片_20241129184650](https://github.com/user-attachments/assets/fb8ed368-3cb5-45f6-8be8-0482418c6654)

**Comment by luigifreda** [comment]
Hi,
Can you share what is your OS and what is the exact install procedure you followed?

**Comment by coutrol** [comment]
> Hi, Can you share what is your OS and what is the exact install procedure you followed?

Hello, glad for your reply, my operating system is ubuntu20.04, I am running ./install_dependencies.sh, ./install_local_opencv.sh, ./build.sh according to your suggestion, these errors are all errors when running the ./build_thirdparty.sh steps in ./build.sh

**Comment by luigifreda** [comment]
Hi,
I've just tested it again under `ubuntu20_cuda` with 
https://github.com/luigifreda/rosdocker

Everything builds fine.  I frequently use a native Ubuntu 20 as a development environment and have no problems. 
Are you using a native Ubuntu 20?
Can you try `rosdocker` with `ubuntu20_cuda` or `ubuntu20`?
