### ISSUE TITLE
Camera.fovScale

### ISSUE THREAD

**Issue by HJMGARMIN** [luigifreda/plvs#8]
Hello, I notice that the param "Camera.fovScale" in TUM-VI_rectified.yaml. I run PLVS on OpenLORIS-Scene dataset. The dataset consists of stereo fisheye images, and I set Camera.fovScale as  0.5. However, the viewer looks a little strange.
I want to know the role of the variable "Camera.fovScale" and what should I set it for different fisheye datasets.
![image](https://github.com/luigifreda/plvs/assets/52454672/60967343-6b13-4519-b5a4-bbec4439fe13)
The raw fisheye image is as below:
![image](https://github.com/luigifreda/plvs/assets/52454672/59167db3-1b70-4fc7-8373-117203eacb64)

**Comment by luigifreda** [comment]
Hi,
as for the `Camera.fovScale` param, take a look here as an entry point 
https://github.com/luigifreda/plvs/blob/master/src/Settings.cc#L567
and refer here for further details 
https://docs.opencv.org/4.x/db/d58/group__calib3d__fisheye.html#gac1af58774006689056b0f2ef1db55ecc

Cheers,
Luigi
